### ISSUE TITLE
Add country information popup when a country is clicked on.

### ISSUE THREAD

**Issue by SeanKennyNF** [PathoTracker/Pathotracker#108]
> Show Number of studies and then seroprev per country (add hover over country metadata like in serotracker.com)

Below is a screenshot of what a country information modal looks like on https://serotracker.com. I'm thinking we'd have to throw the popup in `PathogenCountryHighlightLayer` honestly, that's where the country vectors live and clicking on a country would click on that layer so I think this popup has to live in that layer also. I'm thinking we could fetch the number of estimates for each pathogen and the median seroprevalence of each pathogen per country. Let's maybe start with that and then if we want more information let's hit that as part of a separate ticket.

![image](https://github.com/PathoTracker/Pathotracker/assets/86806388/c5e78b2a-e692-405f-9377-6dcd8e519053)

**Comment by HimanshuRanka** [comment]
Work with Mairead and Harriet to get this figured out!

**Comment by HimanshuRanka** [comment]
For the country popup! the data we want is number of estimates per pathogen per country. So heading being: Number of estimates and then a list like:

ZIKA: 1234
DENGUE: 1234 etc.

**Comment by SeanKennyNF** [comment]
This is ready for review and we should be able to merge it on Sunday so that it's ready for the interviews you folks would like to do next week @harrietware. There's screenshots and gifs over in this PR if you want to take a quick peek but it's basically just what we discussed https://github.com/PathoTracker/Pathotracker/pull/157

cc @EliasPinno I know this was assigned to you but I figured you're a busy bee and we wanted this for Monday so I just knocked it out, we can look over it together tomorrow morning :)
