### ISSUE TITLE
Clicking on a visualizations expands it

### ISSUE THREAD

**Issue by HimanshuRanka** [PathoTracker/Pathotracker#118]
When u click on a visualization it expands to take up the full screen size with more details.

**Comment by HimanshuRanka** [comment]
@SeanKennyNF  Per yesterdays discussion, might be a good idea to hold off on this till after we redesign the pages to have it all in the same place no? 

Do you think the expansion will be agnostic of that change?

**Comment by SeanKennyNF** [comment]
I think the expansion should be agnostic of the change and we're good to go but here's the pull request for reference! Seems like pretty minimal changes to do when we switch over to the new design :)
https://github.com/PathoTracker/Pathotracker/pull/125
