### ISSUE TITLE
Consolidate the Dashboard and the Analyz pages

### ISSUE THREAD

**Issue by HimanshuRanka** [PathoTracker/Pathotracker#136]
Use the Figma here to consolidate the dashboard and analyze page

https://www.figma.com/file/BKtEVRMNkZYh4EbG9T5wp5/PathoTracker?type=design&node-id=309-74&mode=design&t=pahP1zEB6Sp9J4Th-4

The final result should look like the frames below the large one

we want there to scroll snapping. So if a user were to begin scrolling, if they scrolled past the 33% point then the site would automatically snap to the next frame. Similar when scrolling up. 

Additionally we want the 3 sections to be navigatable to. Using an html ID param so that we can navigate to a specific part using the nav bar.

**Comment by HimanshuRanka** [comment]
It will be important to consider the impact this will have on our state management system. Would we even continue to need it? Is there any use case where the user would navigate away from a dashboard and back expecting the filters to remain? Would we want to consider using local storage to save the filter values when a user navigates away from a page, and then load them back in when navigated to the page? 

I think this would be open to discussion so a part of this ticket would be to figure out the implications of the above consolidation and presenting them to the team. Naturally if the resolution seems straightforward then feel free to go ahead and implement it

**Comment by HimanshuRanka** [comment]
Another thing to keep in mind is that the data section and the visualizations sections also look slightly different. Those changes are also included in here

**Comment by HimanshuRanka** [comment]
This is a big boy ticket

**Comment by SeanKennyNF** [comment]
Open to discussion but 
- I think it's a good idea to keep our context + state management stuff, I really don't want to prop drill a bunch of stuff and I like the setup we have. There's also the visualization pages and potentially more in the future that need that state so let's leave that as-is.
- Let's make a separate ticket if we want the filters to persist in local storage or a cookie or something, to me that's not mutually exclusive with keeping the state management system and doesn't have to be tied in with the redesign.
