### ISSUE TITLE
Bug Report on Pathotracker

### ISSUE THREAD

**Issue by HimanshuRanka** [PathoTracker/Pathotracker#2]
Go to the pathotracker website: https://pathotracker.vercel.app/

Explore the sight. Get familiar with the pages and the functionalities. Play around with all the different features and make a note of any buggy impl along with any feature enhancements/updates that you would like to do. 

Put your insights into this spreadsheet: https://docs.google.com/spreadsheets/d/1rSXLnvsO6NJPZ77DfiC4ngcfw_5mbAphxE1qo0G2268/edit#gid=0

This is mostly an introduction to the platform, the work we do, it's use cases etc. It will also help us come up with tasks that need to be done as well as tasks you will specifically like to work on and see improvements on. 

Feel free to come in here and create an issue on a specific bug/feature that you feel strongly about having a solution to and we can review it asynchronously and get started on the work.

For the rest of the bugs, we will work together on Monday standup to sort and generate issues with AC and requirements so we have work that can be picked up.

**Comment by SeanKennyNF** [comment]
I left some bugs/suggestions in the sheet. If I've got any more before Monday or even after Monday I'll put them in the sheet as well. We can talk on Monday and see how many suggestions we have and where we want to go to next :)

Please let me know if there's anything I can help out with in the meantime of course!

**Comment by SeanKennyNF** [comment]
Marked as done in the Kanban board, also closing issue.
