### ISSUE TITLE
Update the About page

### ISSUE THREAD

**Issue by HimanshuRanka** [PathoTracker/Pathotracker#21]
The data on the about page at the moment is highly outdated and irrelevant in a lot of ways and places. This needs to be updated under guidance from Mairead, Harriet and Sabah

**Comment by SeanKennyNF** [comment]
Merged into https://github.com/PathoTracker/Pathotracker/issues/132 and closed. We can hit this as a part of the redesign effort I think since the about page doesn't exist in the current iteration. Let me know if we want to revive this ticket though :)
