### ISSUE TITLE
Update Sero Filter Bar

### ISSUE THREAD

**Issue by HimanshuRanka** [PathoTracker/Pathotracker#26]
Pending discussion:

Filters needed: 
* PENDING

Update the arbotracker filter bar to 
* have informative tool tips
* Be subdivided by category of filtler
* Have a reset filters button

**Comment by SeanKennyNF** [comment]
@HimanshuRanka

I believe this was addressed in this PR (https://github.com/PathoTracker/Pathotracker/pull/41) so I'm going to go ahead and close this issue. If there's a requirement I missed here and you'd rather re-open this please let me know :)
