### ISSUE TITLE
Add LINK button to arbo table

### ISSUE THREAD

**Issue by HimanshuRanka** [PathoTracker/Pathotracker#29]
The link button should take a user to the url provided for that estimate. Each row on the data table should have a link button. 

Alternatively would a better appraoch be to highlight some unique field that is clickable instead of needing a button? Consider the same - Check with Harriet and Mairead on what the users will find most useful

**Comment by HimanshuRanka** [comment]
For now we went with the approach of having a LINK button. The text in the link button is the domain of the URL

**Comment by SeanKennyNF** [comment]
I believe addressed in https://github.com/PathoTracker/Pathotracker/pull/36. Going to close if that's alright!
