### ISSUE TITLE
Modal Redesign

### ISSUE THREAD

**Issue by SeanKennyNF** [PathoTracker/Pathotracker#42]
**Last edit: Nov 30 2023 2:15PM MST**

Based on my understanding of Mairead's suggestion's on Nov 21st.

- [x] Modal heading should be changed from "CHIKV Estimate Study", "ZIKV Estimate Study", etc. to "CHIKV Estimate", "ZIKV Estimate".
- [ ] The url to the study with a hyperlink to that url should be replaced with the name of the study which is still hyperlinked to the url of the study.
- [x] The gray ribbon on the modal where seroprevalence is should match the colour of the study, Ex. green for West Nile Virus, light blue for Chikungaya Virus, etc.
- [x] The gray ribbon should also include "Arbovirus: Zika Virus" or "Arbovirus: West Nile Virus", etc.
- [x] The sampling date should be in it's own column and not bunched together with the seroprevalence.
- [x] LatLng row should be removed
- [x] "Pathogen: ZIKV" or "Pathogen: WNV" at the bottom of the modal should be removed.

Questions:
- Should "Antigen" row be removed?
- Should we do something about "Antibody Target"? Should the name of the column be "Isotype"? (Possibly misunderstanding)

**Comment by harrietware** [comment]
Minor change: I think "CHIKV Estimate" or "ZIKV Estimate" should remain as the heading (but remove "Study") and below this the name of the study which should hyperlink to the study

This helps convey that there are multiple estimates per study displayed on the dashboard, as opposed to SeroTracker where there is only one estimate per study displayed

**Comment by SeanKennyNF** [comment]
@harrietware 

Sounds good! I've made the adjustment in the text of the issue :)
