### ISSUE TITLE
Sampling date filter

### ISSUE THREAD

**Issue by SeanKennyNF** [PathoTracker/Pathotracker#43]
Based on my understanding of Mairead's suggestions on November 21st.

There should be an additional filter to only see studies whose sampling period included dates in a certain range.
I'm thinking that maybe the filter has a start date and an end date and any study whose sampling end date is before the start date of the filter gets filtered out and any study whose sampling start date is after the end date gets filtered out.

Likely important because it's possible to find studies whose sampling end date is in the 1960s which is probably less relevant to the modern landscape than a collection of more recent studies.

**Comment by HimanshuRanka** [comment]
Start Date and End Date field instead of slider (slider not as intuitive)

**Comment by SeanKennyNF** [comment]
Resolved in https://github.com/PathoTracker/Pathotracker/pull/73
