### ISSUE TITLE
Make the left edge of the table in the analysis tab draggable such that someone can expand the table by compressing the graphs to the side or vice versa

### ISSUE THREAD

**Issue by SeanKennyNF** [PathoTracker/Pathotracker#50]
Based on my understanding of Mairead's suggestions on November 21st.

We want the left edge of the table in the analysis tab in Arbotracker to be draggable such that such that someone can expand the table by compressing the graphs to the side or vice versa.

This is the left edge that is being referred to:
![image](https://github.com/PathoTracker/Pathotracker/assets/86806388/a51dad9b-c0de-41d5-bdb6-da4ee7fd3cbb)

**Comment by harrietware** [comment]
What about freezing the first column of the table while scrolling horizontally?

**Comment by SeanKennyNF** [comment]
Sorry @harrietware!

Yeah that suggestion makes sense to me. I think that's a separate feature though and I'm not sure if the dev team would want to take both of these tasks on as a part of the same ticket especially since I'm not 100% sure how difficult that would be with our current table library so I might want to decouple these two things if that's okay :)

https://github.com/PathoTracker/Pathotracker/issues/102

**Comment by SeanKennyNF** [comment]
I'm going to close this issue. Adding the ability to compress the table won't be necessary with the new design since the table occupies basically the full width.
